### ISSUE TITLE
Support/Fix update interval

### ISSUE THREAD

**Issue by Frankkz** [Gerrnperl/ksysguard-colored-text#1]
Been loving this display style! So thanks a lot for making it :).

I did notice that the "Minimum Time Between Updates" setting isn't respected. Other display methods do respect or use this setting.

Example of the config file;
~/.config/plasma-org.kde.plasma.desktop-appletsrc
```
[Containments][27][Applets][79][Configuration][Appearance]
chartFace=org.gerrnperl.text
showTitle=true
title=CPU
updateRateLimit=1000
```
Even though it says 1000ms, it is actually updating at multiple times per second.

Would it be possible to add support for this? 

Thanks.

**Comment by Frankkz** [comment]
https://github.com/Gerrnperl/ksysguard-colored-text/blob/11897c0ae754c5ce1dce23643f3153b05e9e4069/contents/ui/TotalSensor.qml#L36-L39

I don't know if this is the correct implementation but adding `updateRateLimit: root.controller.updateRateLimit` to the above will make it respect the setting.

**Comment by Gerrnperl** [comment]
Thank you for your support, I have applied your suggestion in the new version.
